apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-publish
  title: Test Publish Multi-Providers
  description: Test Repository Publishing in Multi-Providers
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - recommended
    - platform-templates
spec:
  owner: veecode/platform
  type: service
  parameters:
    - title: Project Configuration
      required:
        - componentId
        - owner
      properties:
        componentId:
          title: Project name
          type: string
          description: Name of the project
          pattern: "^([a-z0-9]|[.]|[_]|[-])*$"
          ui:autofocus: true
          ui:field: EntityNamePicker
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
        description:
          title: Description
          type: string
          description: Help others understand what this application is for.

    - title: Git Provider
      required:
        - gitProvider
      properties:
        gitProvider:
          title: Choosee your git provider
          type: string
          enum:
            - github
            - gitlab
          enumNames:
            - 'Github'
            - 'Gitlab'
          default: github
      description: Select the Git provider where you want to publish your repository.

    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
              - gitlab.com
              - bitbucket.org
        visibility:
          title: Repository visibility
          type: string
          enum:
            - public
            - private
          enumNames:
            - "Public"
            - "Private"
          default: private

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          componentId: ${{ parameters.componentId }}
          description: ${{ parameters.description }}
          gitProvider: ${{ parameters.gitProvider }}
          owner: ${{ parameters.owner }}
          repoUrl: ${{ (parameters.repoUrl | parseRepoUrl).owner }}/${{ (parameters.repoUrl | parseRepoUrl).repo }}
          host: ${{ (parameters.repoUrl | parseRepoUrl).host }}

    - id: publish
      name: Publish in Github
      if: ${{ parameters.gitProvider  === "github" }}
      action: publish:github
      input:
        allowedHosts:
          - github.com
        description: This is ${{ parameters.componentId }}
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: ${{ parameters.visibility }}

    - id: publish
      name: Publish in Gitlab
      if: ${{  parameters.gitProvider  === "gitlab" }}
      action: publish:gitlab
      input:
        allowedHosts:
          - gitlab.com
        description: This is ${{ parameters.componentId }}
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: ${{ parameters.visibility }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
