apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.componentId }}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    ${{ values.host }}/project-slug: ${{values.repoUrl}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}